### ISSUE TITLE
Breaks emmet in jsx files

### ISSUE THREAD

**Issue by danalexilewis** [capaj/vscode-standardjs-snippets#6] opened 2017-07-11 19:46 UTC
I have narrowed it down to this plugin.

When I am editing jsx and type div + [tab] i expect it to create `<div></div>` 

Instead `div ` is output

if you tab again `div name`

vscode 1.13.1

If you need more info let me know

**Comment by capaj** [comment] 2017-07-12 21:34
I am not able to reproduce that. Could you maybe post a video?

**Comment by capaj** [comment] 2018-12-25 21:46
this might have been a bug in vscode itself. Closing as this cannot be reproduced.

**Closed as completed by capaj** 2018-12-25 21:46 UTC
